### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by phoebe-lew**

### CODE REVIEW

**Review by mistermoe — COMMENTED** [review]
Let's add @amika-sq too and point @tomdaffurn to aws key manager

**Review by diehuxx — APPROVED** [review]
nice

**Review by nitro-neal — APPROVED** [review]

**Comment by mistermoe** [comment]
Oops sorries. You already added @amika-sq . Code reviews on mobile are hard

**Comment by lamchau** [comment]
do y'all use `@username` over `@org/team-name` for security reasons or something else? just curious!

**Pull request merged**
