### PR TITLE
Updating to JsonWebKey

### PR DESCRIPTION
**Pull request by nitro-neal**
Fixes - https://github.com/TBD54566975/web5-spec/issues/73

### CODE REVIEW

**Review by phoebe-lew — APPROVED** [review]

**Comment by jiyoontbd** [comment]
@nitro-neal are we _removing_ JsonWebKey2020 or also supporting JsonWebKey in addition? i asked about this in our internal slack and @frankhinek said we should support both for a while, so that's what my PR had

slack thread with frank's comment [here](https://sq-tbd.slack.com/archives/C05SXUR39FE/p1707149448364429?thread_ts=1707148978.096459&cid=C05SXUR39FE)
my PR [here](https://github.com/TBD54566975/tbdex-kt/pull/149/files#diff-440c5a82f202ec6f559e38eb7d28ffd42d08a16744348aa9f9bd305657ce303bR95)

**Comment by nitro-neal** [comment]
@jiyoontbd yup I'm getting this one in: https://github.com/TBD54566975/web5-kt/pull/233 then once it works with jsonwebkey2020 and jsonwebkey I can merge this one in and it will work with both

**Comment by jiyoontbd** [comment]
looks like this one can be merged now @nitro-neal ?

**Comment by nitro-neal** [comment]
Closing as ion is going away and this will need a large refactor, will revisit in the future

**Pull request closed without merging**
