### PR TITLE
downgrading kotlin

### PR DESCRIPTION
**Pull request by nitro-neal**
# Overview
Addresses https://github.com/TBD54566975/web5-kt/issues/48

# Description
TBDiligence uses:
image

### CODE REVIEW

**Review by andresuribe87 — APPROVED** [review]

**Comment by mistermoe** [comment]
Yoo! i might be missing context here bc i'm not sure what y'all tried before this, i know y'all tried quite a bit of stuff. I feel like this fixes the problem for tbdiligence but it seems strange that the minor version of kotlin we're using for this lib must match the minor version of kotlin that downstream consumers are using.

feels like there oughta be some compatibility option like "compile such that it works with minimum 1.7.0" or something along those lines.

otherwise we're going to end up in a situation where we're constantly changing versions depending on the kotlin version that  our downstream consumers are using

**Comment by mistermoe** [comment]
@nitro-neal looks like we can specify kotlin version compat - [docs here](https://kotlinlang.org/docs/gradle-compiler-options.html#attributes-common-to-jvm-and-js)

image


in the root `build.gradle.kts` within `subprojects` might be worth trying:

```
  kotlin {
    explicitApi()
    jvmToolchain(11)
    compilerOptions {
      jvmTarget.set(JvmTarget.JVM_11)
      apiVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_1_7)
      languageVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_1_7)
    }
  }

  java {
    targetCompatibility = JavaVersion.VERSION_11
    withJavadocJar()
    withSourcesJar()
  }
```

**Comment by nitro-neal** [comment]
no good, when I try to do the above and consume it with our test app
still getting:

Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by nitro-neal** [comment]
Also I need to confirm, but I think that if any consuming app is our version or later it will work, doesn't have to be the exact same version

**Comment by mistermoe** [comment]
yoo @nitro-neal i think we can close this out yeah?

**Pull request closed without merging**
